language: java

services:
  - docker

before_install:
- docker pull nats-streaming
- docker run -p 4222:4222 -p 8222:8222 -d  nats-streaming
- docker pull postgres
- docker run -p 5432:5432 -e POSTGRES_PASSWORD=mewbase -e POSTGRES_USER=mewbase -d
- docker ps -a

jdk:
- oraclejdk8
- oraclejdk9

script:
- mvn clean package

branches:
  only:
    - master

after_failure:
- cat  /home/travis/build/Tesco/mewbase/*.log