language: java

services:
  - docker

before_install:
# These are all here ready for automated testing via various configs

# Hold the bus while we work out collision with DockerCompose
# - docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 -d spotify/kafka
# - docker run -p 4222:4222 -p 8222:8222 -d  nats-streaming
# - docker run -p 5432:5432 -e POSTGRES_PASSWORD=mewbase -e POSTGRES_USER=mewbase  # port collision with DockerCompose
# - docker run -p8161:8161 -p 61616:61616 -d -e ARTEMIS_USERNAME=admin -e ARTEMIS_PASSWORD=admin vromero/activemq-artemis
# - docker ps -a

jdk:
- oraclejdk8
- oraclejdk9

script:
- sbt clean compile test package

branches:
  only:
    - master

after_failure:
- cat  /home/travis/build/Tesco/mewbase/*.log
